// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zavxkbbwbrxnkfipfwip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdnhrYmJ3YnJ4bmtmaXBmd2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NTU5MjIsImV4cCI6MjA1MDEzMTkyMn0.izPb5dl1ISJK6JiEJDdzfo953pOsOud96hFsfDCLx04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);